// Generate firebase_options.dart for CI
import 'dart:io';

void main() {
  final apiKey = Platform.environment['FIREBASE_API_KEY'] ?? 'YOUR_API_KEY';
  final appId = Platform.environment['FIREBASE_APP_ID'] ?? 'YOUR_APP_ID';
  final senderId =
      Platform.environment['FIREBASE_MESSAGING_SENDER_ID'] ?? 'YOUR_SENDER_ID';
  final projectId =
      Platform.environment['FIREBASE_PROJECT_ID'] ?? 'YOUR_PROJECT_ID';
  final storageBucket = Platform.environment['FIREBASE_STORAGE_BUCKET'] ??
      '$projectId.appspot.com';

  final configured = apiKey != 'YOUR_API_KEY' && projectId != 'YOUR_PROJECT_ID';

  final content = '''
// Generated by tools/generate_firebase_options_ci.dart in CI

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static bool get isConfigured => $configured;

  static const String _apiKey = '$apiKey';
  static const String _appId = '$appId';
  static const String _messagingSenderId = '$senderId';
  static const String _projectId = '$projectId';
  static const String _storageBucket = '$storageBucket';
  static const String _authDomain = '${projectId}.firebaseapp.com';

  static FirebaseOptions get currentPlatform {
    if (!isConfigured) {
      throw UnsupportedError('Firebase is not configured.');
    }
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    authDomain: _authDomain,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
    iosBundleId: 'com.example.aptitudeTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _apiKey,
    appId: _appId,
    messagingSenderId: _messagingSenderId,
    projectId: _projectId,
    storageBucket: _storageBucket,
  );
}
''';

  File('lib/firebase_options.dart').writeAsStringSync(content);
  stdout.writeln('Generated lib/firebase_options.dart (configured=$configured)');
}
